ARG from=ubuntu:focal
FROM $from

LABEL maintainer="Christophe Trophime <christophe.trophime@lncmi.cnrs.fr>"

ARG USERNAME=feelpp
ARG VERSION=1.0.6

# Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

USER root
RUN apt-get -qq update && \
    apt-get -y --no-install-recommends install sudo openssh-client

# to help debug but shall not be present in prod
RUN useradd -m -s /bin/bash -G sudo,video $USERNAME && \
    mkdir -p  /etc/sudoers.d/ && \
    echo "$USERNAME ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/$USERNAME && \
    chmod 0440 /etc/sudoers.d/$USERNAME && \
    mkdir -p ~$USERNAME/.ssh/ && \
    ssh-keyscan github.com >> ~$USERNAME/.ssh/known_hosts && \
    chown -R $USERNAME ~$USERNAME/.ssh

# Seup demo environment variables
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    LC_ALL=C.UTF-8 \
    PATH=$PATH:/home/$USERNAME/.local/bin

RUN apt-get -qq update && \
    apt-get -y upgrade && \
    apt-get -y --no-install-recommends install debian-keyring lsb-release ca-certificates curl && \
    apt-get -y --no-install-recommends install cmake git clang g++ gfortran dpkg-dev && \
    apt-get -y --no-install-recommends install python3 python3-pip python3-setuptools python3-venv python-is-python3 libpython3-dev swig libpq-dev && \
    cp /usr/share/keyrings/debian-maintainers.gpg /etc/apt/trusted.gpg.d

RUN echo "lsb_release=$(lsb_release -cs)"
RUN echo "*** install prerequisites for MagnetTools ***" && \
    echo "deb http://euler.lncmig.local/~christophe.trophime@LNCMIG.local/debian/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/lncmi.list && \
    echo "deb-src http://euler.lncmig.local/~christophe.trophime@LNCMIG.local/debian/ $(lsb_release -cs) main" >> /etc/apt/sources.list.d/lncmi.list && \
    apt-get -qq update && \
    apt-get -y --no-install-recommends install libyaml-cpp-dev libjson-spirit-dev libgsl-dev libfreesteam-dev \
         libpopt-dev zlib1g-dev libeigen3-dev fadbad++ libgnuplot-iostream-dev \
         libsphere-dev libsundials-dev libmatheval-dev libexpokit-dev
     

# ffmpeg for matplotlib anim & dvipng+cm-super for latex labels
RUN apt-get update && \
    apt-get install -y --no-install-recommends ffmpeg dvipng cm-super && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Switch back to dialog for any ad-hoc use of apt-get
ENV DEBIAN_FRONTEND=dialog

USER $USERNAME
WORKDIR /home/$USERNAME

# Install properly MagnetTools into poetry env
# create MagneTools wheel package
RUN cd /home/${USERNAME} \
    && curl -sSL https://install.python-poetry.org | python -  \
    && poetry --version \
    && echo "get magnettools source" \
    && sudo apt-get update \
    && apt-get source magnettools \
    && cd magnettools-${VERSION} \
    && mkdir -p build \
    && cd build \
    && cmake .. \
      -DMAGNETTOOLS_ENABLE_OPTIONALDEPS=ON \
      -DMAGNETTOOLS_ENABLE_PYTHON=ON \
      -DMAGNETTOOLS_PYTHON_VERSION=3 \
    && make \
    && cd Python \
    && echo "MagnetTools Python Bindings" > magnettools/README.md \
    && cd /home/$USERNAME \
    && cp magnettools-${VERSION}/build/Python/dist/magnettools-${VERSION}-py3-none-any.whl \
    && rm -rf magnettools-${VERSION} magnettools_${VERSION}*
    

WORKDIR /home/$USERNAME
